const CONSTANT = {
  CREATE_GAME_DATA: 'CREATE_NEW_GAME_DATA',
  NEW_TETRIS_GAME_SESSION: 'NEW_TETRIS_GAME_SESSION',
  TETRIS_GAME_SESSION_DATA: 'TETRIS_GAME_SESSION_DATA',
  JOIN_TETRIS_GAME_SESSION: 'JOIN_TETRIS_GAME_SESSION',
  START_TETRIS_GAME_SESSION: 'START_TETRIS_GAME_SESSION',
  START_TETRIS_GAME: 'START_TETRIS_GAME',
  TETRIS_GAME_ROOM_SIZE: 'TETRIS_GAME_ROOM_SIZE',
  PLAYER_JOIN_GAME_ROOM: 'PLAYER_JOIN_GAME_ROOM',
  INVALID_TETRIS_GAME_ROOM: 'INVALID_TETRIS_GAME_ROOM',
  USERNAME_TAKEN_ERROR: 'USERNAME_TAKEN_ERROR',
  DELETE_GAME_SESSION: 'DELETE_GAME_SESSION',
  UPDATED_ROOM_MEMBER_STATE: 'UPDATED_ROOM_MEMBER_STATE',
  UPDATED_GAME_SESSION_DATA: 'UPDATED_GAME_SESSION_DATA'
};

export default CONSTANT;
