const CONSTANT = {
  CREATE_GAME_DATA: 'CREATE_NEW_GAME_DATA',
  NEW_TETRIS_GAME_SESSION: 'NEW_TETRIS_GAME_SESSION',
  TETRIS_GAME_SESSION_DATA: 'TETRIS_GAME_SESSION_DATA',
  JOIN_TETRIS_GAME_SESSION: 'JOIN_TETRIS_GAME_SESSION',
  START_TETRIS_GAME_SESSION: 'START_TETRIS_GAME_SESSION',
  START_TETRIS_GAME: 'START_TETRIS_GAME',
  INVALID_TETRIS_GAME_ROOM: 'INVALID_TETRIS_GAME_ROOM',
  USERNAME_TAKEN_ERROR: 'USERNAME_TAKEN_ERROR'
};

export default CONSTANT;
